apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hi14j0znw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hi14j0znw-go 
  name: hi14j0znw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hi14j0znw-go 
